### ISSUE TITLE
Error : docker-tinode-rethinkdb-master_server_1 exited with code 127

### ISSUE THREAD

**Issue by ghost** [imikiani/docker-compose-tinode-rethinkdb#1]
Hi,

Thank you very much for this work!
I'm trying to launch your docker image but unfortunately I have an error:
docker-tinode-rethinkdb-master_server_1 exited with code 127

Thanks for your help

**Comment by imikiani** [comment]
@Tofdu31 
Hi,
Sorry for my delay.

I've just added the readme. Follow the instruction in the readme and if there were any problems, please inform me to solve them.

Thank you so much for choosing this repo.

**Comment by ghost** [comment]
OK thank
